# Generated by Django 3.2.25 on 2024-06-01 20:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_image",
            field=models.ImageField(blank=True, null=True, upload_to="article_images/"),
        ),
        migrations.AlterField(
            model_name="article",
            name="body",
            field=tinymce.models.HTMLField(),
        ),
    ]
