version: '3'

services:
  web:
    build: .
    command: gunicorn django_blog.wsgi:application --bind 0.0.0.0:${PORT:-8000}
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:${PORT:-8000}"
    env_file:
      - .env
