version: '3'

services:
  web:
    build: .
    command: gunicorn --timeout 120 django_blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
