version: '3'

services:
  web:
    build: .
    command: gunicorn django_blog.wsgi:application --bind 0.0.0.0:${PORT:-8000}
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:${PORT:-8000}"
    env_file:
      - .env
  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
